# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.consoleLogLevel = 0;
  boot.kernelParams = [ "quiet" ];
  boot.plymouth.enable = true;
  boot.initrd.verbose = false;
  boot.loader.timeout = 0;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fd9312ef-1845-40fe-9233-70c77d350086";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8F14-D8B1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/00f2da24-f381-4e2b-9c26-6826b111dc3e";
      fsType = "btrfs";
    };

  fileSystems."/mnt/linuxgames" = 
    { device = "dev/disk/by-uuid/757d02dc-f516-4f45-b1aa-922733eb90ae";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
